### PR TITLE
Handle clojure.spec exceptions

### PR DESCRIPTION
**Pull request by flyboarder**
Clojure.spec cannot be serialized, ~~this PR will catch the NotSerializableException and throw the original exception early.~~ **Update: See last comment.**

### CODE REVIEW

**Comment by flyboarder** [comment]
Note: the file paths in the exception will refer to the tmp locations, `handle-ex` does not work for related clojure.spec exceptions.

**Comment by flyboarder** [comment]
This PR will show errors related to #177

**Comment by flyboarder** [comment]
I have improved this PR.

@Deraen now makes 3 changes:

1. Check for `clojure.spec.alpha/spec` and `clojure.spec/spec` in data and remove from exception. (Clojure specs cannot be serialized.)
2. Remove the original exception from `ex-info`, ie. do not provide 3rd argument as it still contains the specs.
3. Include a catch for any other serialization related issues and re-throw the original exception.

**Comment by Deraen** [comment]
Thanks, I'll have to think about this. I including spec data would probably be useful, if possible somehow.

Rethrowing original exception if it can't be serialized is probably good idea.

**Comment by flyboarder** [comment]
@Deraen is there a reason we serialize at all? It looks like we just do it to return the map which throws anyway. Seems we could skip the serialization and throw after `handle-ex`?

**Pull request merged**
